import { AlertTriangle, PackagePlus, Pencil, Save, Search, ShoppingBag, Trash2, X } from "lucide-react";
import { useState } from "react";
import { formatCurrency } from "./data";
import { useAppStore, type StoredProduct } from "./store";

export function StoreProducts() {
  const { products, saveProduct, softDeleteProduct } = useAppStore();
  const [search, setSearch] = useState("");
  const [editor, setEditor] = useState<StoredProduct | "new" | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<StoredProduct | null>(null);
  const visible = products.filter((item) => item.active && `${item.name} ${item.id} ${item.type}`.toLowerCase().includes(search.toLowerCase()));

  return (
    <section className="acceptance-page">
      <header className="acceptance-page-header"><span className="acceptance-page-icon"><ShoppingBag size={30} /></span><div><span className="eyebrow">Data master</span><h2>Produk</h2><p>Perubahan produk tersimpan pada store bersama dan riwayat Bon tetap memakai snapshot.</p></div><button className="button button--primary" type="button" onClick={() => setEditor("new")}><PackagePlus size={20} />Tambah Produk</button></header>
      <section className="acceptance-toolbar"><label className="search-box"><Search size={21} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari produk" /></label><span>{visible.length} produk aktif</span></section>
      <div className="acceptance-product-list">{visible.map((product) => <article className="acceptance-product-card" key={product.id}><span className="product-icon"><ShoppingBag size={24} /></span><div><span className="eyebrow">{product.id}</span><h3>{product.name}</h3><span className={`status-badge status-badge--${product.type.toLowerCase()}`}>{product.type}</span><div className="acceptance-product-facts"><span>Harga Base <strong>{formatCurrency(product.basePrice)}</strong></span><span>Harga Modal <strong>{formatCurrency(product.costPrice)}</strong></span><span>Stok <strong>{product.stock}</strong></span></div></div><div className="acceptance-product-actions"><button className="button button--secondary button--compact" type="button" onClick={() => setEditor(product)}><Pencil size={18} />Edit</button><button className="button button--danger button--compact" type="button" onClick={() => setDeleteTarget(product)}><Trash2 size={18} />Nonaktifkan</button></div></article>)}</div>
      {editor && <ProductEditor value={editor === "new" ? undefined : editor} nextId={`PRD-${String(products.length + 1).padStart(3, "0")}`} onClose={() => setEditor(null)} onSave={(product) => { saveProduct(product); setEditor(null); }} />}
      {deleteTarget && <div className="dialog-backdrop acceptance-dialog-backdrop" role="presentation" onMouseDown={() => setDeleteTarget(null)}><section className="acceptance-confirm-dialog" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><AlertTriangle size={36} /><h2>Nonaktifkan produk?</h2><p>{deleteTarget.name} tidak lagi muncul pada transaksi baru. Snapshot pada Bon lama tetap utuh.</p><div><button className="button button--secondary" type="button" onClick={() => setDeleteTarget(null)}>Batal</button><button className="button button--danger" type="button" onClick={() => { softDeleteProduct(deleteTarget.id); setDeleteTarget(null); }}>Nonaktifkan</button></div></section></div>}
    </section>
  );
}

function ProductEditor({ value, nextId, onClose, onSave }: { value?: StoredProduct; nextId: string; onClose: () => void; onSave: (product: StoredProduct) => void }) {
  const [draft, setDraft] = useState<StoredProduct>(value ?? { id: nextId, name: "", type: "LM", basePrice: 0, costPrice: 0, stock: 0, active: true });
  const valid = draft.name.trim().length > 0 && [draft.basePrice, draft.costPrice, draft.stock].every((amount) => Number.isFinite(amount) && amount >= 0);
  return <div className="dialog-backdrop acceptance-dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="acceptance-master-dialog acceptance-master-dialog--small" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">Data produk</span><h2>{value ? "Edit Produk" : "Tambah Produk"}</h2><p>Harga Modal tidak ditampilkan kepada pelanggan.</p></div><button className="icon-button" type="button" onClick={onClose}><X size={22} /></button></header><div className="acceptance-master-body"><div className="acceptance-form-grid"><label className="field field--wide"><span>Nama produk *</span><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label className="field"><span>Kode</span><input value={draft.id} disabled /></label><label className="field"><span>Tipe *</span><select value={draft.type} disabled={Boolean(value)} onChange={(event) => setDraft({ ...draft, type: event.target.value as "LM" | "BR" })}><option value="LM">LM</option><option value="BR">BR</option></select><small>{value ? "Tipe dikunci agar klasifikasi riwayat tetap konsisten." : "Pilih klasifikasi produk."}</small></label><label className="field"><span>Harga Base *</span><input type="number" min={0} value={draft.basePrice} onChange={(event) => setDraft({ ...draft, basePrice: Math.max(0, Number(event.target.value) || 0) })} /></label><label className="field"><span>Harga Modal *</span><input type="number" min={0} value={draft.costPrice} onChange={(event) => setDraft({ ...draft, costPrice: Math.max(0, Number(event.target.value) || 0) })} /></label><label className="field"><span>Stok *</span><input type="number" min={0} value={draft.stock} onChange={(event) => setDraft({ ...draft, stock: Math.max(0, Number(event.target.value) || 0) })} /></label></div></div><footer><button className="button button--secondary" type="button" onClick={onClose}>Batal</button><button className="button button--primary" type="button" disabled={!valid} onClick={() => onSave({ ...draft, name: draft.name.trim() })}><Save size={19} />Simpan Produk</button></footer></section></div>;
}
